ALTER TABLE daily_shifts
  ADD COLUMN IF NOT EXISTS arrive_attempts INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_arrive_attempt_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_arrive_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS last_arrive_lng DOUBLE PRECISION;
